/**
 * Sponsor-match — the UI ⇄ ranker CONTRACT.
 *
 * This file IS the seam. The ranker (`sponsor-match-spine-run.ts`) produces
 * `SponsorMatchResponse`; the console (`components/edit/sponsor-match-panel.tsx`)
 * consumes it and re-ranks with the reference functions below. Both import THIS
 * module, so a drift between them is a compile error rather than a live bug.
 *
 * WHY IT EXISTS: PR #1673 shipped the editable-centrality console against a mockup
 * instead of this contract and violated its central invariant (below). Nothing caught
 * it because the contract was prose only. Prose does not fail CI; this file does.
 *
 * THE INVARIANT (the hinge):
 *
 *     Sliders re-rank LIVE over the already-fetched candidates. No new search.
 *
 * That is only possible if the response carries the DECOMPOSED score inputs per
 * candidate rather than a final scalar:
 *
 *     score(s) = Σ_c  centrality(c)^γ·weightFactor(c) / (K + rank_{s,c}) × (1 + λ·prefBoost(s))
 *                     └──── editable ────┘└─── fixed ───┘   └─ per-candidate, per-concept ─┘
 *
 * `SponsorCandidate.contributions[]` carries `rank_{s,c}` for EVERY concept the
 * candidate appeared under — weak ones included, because they are re-rank inputs, not
 * display data. Ship a final score alone and the rail degrades to "re-query on every
 * drag", which the design rejects (each drag = up to 8 concepts × paged `searchPeople`
 * — seconds, not live).
 *
 * THE WEIGHTING IS NOT FROZEN HERE, AND IT MOVED. `weightFactor` is named for its role in
 * the formula, not its implementation — which is exactly what let the FINDING's fix land as
 * an engine-only change. It is no longer corpus IDF (that axis anti-correlated with topical
 * centrality and ranked a disease BELOW its own mechanisms; see
 * `docs/2026-07-12-FINDING-idf-inverts-concept-weighting.md`). #1676 demoted rarity to a bounded
 * tiebreaker; #1681 removed it from the weight ENTIRELY, having measured the band earning nothing.
 * `weightFactor` is now the paste-relative kind prior alone, and centrality raised to γ does the
 * actual work. Rarity survives as the display-only `corpusCoverage` — a claim about the LITERATURE,
 * never about the RANKING. The route and the panel did not move across any of it. The decomposition
 * is what is frozen here, and the decomposition is right.
 *
 * DERIVED, NOT WIRED: the matched-concept chips and the fit tier are deliberately NOT
 * response fields. Both are computed client-side (`matchedConcepts`, `fitTier`) so they
 * stay live under the sliders instead of going stale the moment one moves.
 *
 * PRODUCER GAP (narrowed again): `measures` has a producer (#1654 — both engines hydrate it
 * via `sponsorMeasuresFrom` below, so career stage, clinician status and person type are
 * real). `preferences` has one (`extractSponsorPreferences`). `ask` now has one too —
 * `sponsorAskFrom` below, DERIVED from the concepts rather than generated by an LLM. `facets`
 * is gone: it was declared, never produced, never read, and every shipped facet is computed
 * client-side from the candidate list.
 *
 * EVIDENCE — and a correction worth keeping, because the wrong diagnosis was written down here
 * and believed. This doc used to say the spine could not produce evidence because it runs
 * `skipFacetAggs`, and that the fix needed "the match-explain aggregation the spine deliberately
 * skips". BOTH CLAIMS WERE FALSE. `skipFacetAggs` gates exactly one thing — the nine People-index
 * FACET aggs — and appears nowhere in the reason-agg's eligibility predicate. The spine produced
 * no evidence for the dullest possible reason: it never passed `matchExplain`, which defaults to
 * false. It never asked.
 *
 * The cost of believing the comment was not zero: acting on it meant dropping `skipFacetAggs`,
 * which would have re-armed the aggregation that tripped the OpenSearch breaker AND still
 * produced no evidence. A doc-comment asserting a mechanism is a hypothesis; this one was wrong
 * for weeks and cost a filed issue that named the wrong cause.
 *
 * The spine now asks (#1689), and carries the search's own `ResultEvidence` on
 * `searchEvidence` — see `SponsorSearchEvidence`. `evidence` (the bespoke shape) remains for
 * the bespoke engine. These stay OPTIONAL so the route never has to fabricate a value to
 * satisfy the type. Absent ≠ zero.
 *
 * `caveat` USED to sit here — a near-miss reason, declared, never written, never read. It is
 * gone rather than left "for later": a demoted-card treatment can be built against it, will
 * typecheck, will pass its tests, and will never fire in production. That is this codebase's
 * most-repeated bug (`abstain`, `measures`, `prefBoost` all shipped inert). "Show anyway"
 * needs a producer FIRST — someone deciding what a near-miss IS and what reason to emit —
 * and the field comes back with it, in that PR.
 *
 * #1696 widened `searchEvidence` from ONE evidence to one PER CONCEPT. The spine fans out a
 * `searchPeople` call per concept and already had every result in hand; shipping only the
 * candidate's best concept threw the rest away after paying for it. A candidate typically
 * matches several concepts, and "why did this scholar match?" is answered badly by one of them.
 * The widening costs ZERO additional retrieval — see the note in `sponsor-match-spine-run.ts`,
 * where that is load-bearing.
 *
 * Note what "came back carrying evidence" does NOT mean, since the phrasing is a trap the first
 * cut of #1696 fell into: `searchPeople`'s ladder ALWAYS returns something (it terminates in
 * `{ kind: "none" }`), so "the call returned evidence" is not the same claim as "the scholar
 * matched this concept". Only entries passing `isResearchMatchEvidence` reach the wire — see
 * `SponsorCandidate.searchEvidence`.
 */
import type { ResultEvidence } from "@/lib/api/result-evidence";
import { careerStageBucket, type CareerStage } from "@/lib/career-stage";

/**
 * RRF damping (pivot handoff §4). The head is damped so one concept's #1 hit cannot
 * dominate the fusion.
 *
 * The server fuses with this K and the client re-ranks with this K — same constant, one
 * definition. They MUST agree or `rerankCandidates` at default weights will not reproduce
 * the order the server sent (see `sponsor-match-contract.test.ts`, which asserts exactly
 * that round-trip).
 *
 * 30 — MEASURED, and it is the middle of a range neither of the previous values found.
 *
 * The original 60 was too flat: ranks 1 and 20 give denominators 61 and 80, a 1.3x spread,
 * so being the single BEST person on the funder's target was worth almost nothing over being
 * twentieth on it. #1676 therefore cut K to 8 (3.1x across the same ranks) — and overshot.
 * At K=8 the head is so peaked that ONE concept's #1 hit can carry a candidate, which is the
 * failure RRF damping exists to prevent; a candidate topping a single peripheral concept
 * out-scores one who is consistently strong across the central ones.
 *
 * Swept over the 15 eval fixtures, re-fusing each from a FIXED extraction so the deltas are
 * the constant's and nothing else (K is a pure fusion parameter — no re-query needed):
 *
 *     K=8 (shipped)  0.6131      K=16  0.6309 (+0.018)      K=30  0.6375 (+0.024)
 *     K=60 (old)     0.6217 — net positive, but it makes 10 of 15 fixtures WORSE
 *
 * A broad plateau from 16 to 60 peaking near 30, not a knife-edge, so this is a real optimum
 * rather than a fit to the fixture set. Reverting to 60 would have been the wrong correction.
 */
export const DEFAULT_K = 30;

/**
 * Exponent on centrality in the fusion weight (FINDING §8.4 — decomposition asymmetry).
 *
 * A sponsor's paste decomposes into ONE primary target and SIX-ish supporting mechanisms,
 * and every cluster votes independently in the RRF. Linear centrality therefore lets the
 * mechanisms out-vote the target by sheer count: a generalist mid-ranked on six mechanisms
 * beats the specialist ranked #1 on the disease. Squaring the centrality makes the primary
 * target dominate its own supporting detail BY CONSTRUCTION rather than by accident —
 * at the post-FINDING rubric (target 1.0, mechanism ~0.5) a cube turns a 2x lead into 8x.
 *
 * 3, not 2: swept on the fixtures, centrality wants MORE authority, not less, once rarity is
 * out of the weight (γ=2 → 0.6483, γ=3 → 0.6532 at K=30). The curve keeps creeping up past 3,
 * but the gain flattens while the risk does not — a large γ makes the ranking hostage to the
 * extractor's centrality being well-calibrated, and a degenerate extraction (the ORIGINAL
 * failure: everything at 1.0) would collapse the weight to the kind prior alone. 3 takes the
 * measured win and stops before the ranker's correctness depends on the LLM being perfect.
 *
 * Shared, like DEFAULT_K: `conceptWeight` is the ONE definition of the weight and both the
 * server's fusion and the client's slider re-rank call it, so client and server cannot
 * drift apart on it (`sponsor-match-contract.test.ts` pins the round-trip).
 */
export const CENTRALITY_GAMMA = 3;

/**
 * Fit-tier bands, as a fraction of the TOP candidate's fused score. The ranker stays
 * presentation-free: it ships `fusedScore` and the UI buckets it, so the tiers re-derive
 * live as sliders move.
 *
 * ponytail: proposed bands, not measured ones — the contract left the thresholds open.
 * They live here as named constants so retuning is a one-line edit in one place rather
 * than a hunt through the panel. Tune against staging once officers have used it.
 */
export const TIER_STRONG = 0.66;
export const TIER_GOOD = 0.33;

/**
 * How many concepts' worth of evidence one candidate card carries (#1696) — the top-K
 * contributions BY STRENGTH at DEFAULT weights, strongest first.
 *
 * A cap is needed because the payload has no natural one: a paste decomposes into up to
 * MAX_TERMS (8) concepts and a strong candidate can rank under all of them, so an uncapped card
 * would stack 8 reason lines — each with its own expandable representative-papers disclosure —
 * on each of 100 rows. That is not "more evidence", it is a wall.
 *
 * 3, and it is a PROPOSED value, not a measured one (like TIER_STRONG / TIER_GOOD above — say
 * so rather than dress it up). The reasoning is the decomposition's own shape (FINDING §8.4): a
 * sponsor's paste is ONE primary target plus supporting mechanisms, so three lines are enough
 * to show an officer that a candidate matched the target AND that the match is not a fluke of
 * one concept — which is the entire point of widening this. Retune it here, in one place, once
 * officers have used the console.
 *
 * STRENGTH, NOT RANK, and the distinction is not academic — it inverts the cap. Strength is
 * `conceptWeight(concept) / (K + rank)`: the term the fusion sums and the quantity
 * `matchedConcepts` orders the chips by. With CENTRALITY_GAMMA = 3, centrality dominates rank,
 * and rank anti-correlates with importance in exactly the wrong direction: a sponsor's PRIMARY
 * concept is its broadest, most competitive query, so a specialist places WORSE on it than on a
 * narrow peripheral mechanism. A rank cap therefore keeps three peripheral mechanisms and slices
 * off the sponsor's actual target — the concept the card leads with as its first chip. Sorting by
 * the score's own term makes the cap keep what the ranking already says matters.
 *
 * The cap counts BLOCKS, not contributions: concepts with no MATCH evidence are dropped BEFORE
 * the slice (see `SponsorCandidate.searchEvidence`), so a candidate whose two strongest concepts
 * are unresolved clusters still ships the three below them rather than a short list.
 */
export const MAX_EVIDENCE_CONCEPTS = 3;

export type SponsorFitTier = "strong" | "good" | "weak";

/**
 * A research concept the funder wants funded — the unit the rail edits.
 *
 * This is the MERGED CLUSTER, not the raw extracted term: "cancer", "oncology" and
 * "leukemia" in one paste collapse to a single concept (equivalence decided by the MeSH
 * descriptor sets, not the LLM) so redundant sponsor phrasing cannot triple-weight one
 * idea. `term` is the cluster's representative — and the join key `contributions[].term`
 * points back to.
 */
export type SponsorConcept = {
  /** Representative term. The join key for `SponsorCandidate.contributions[].term`. */
  term: string;
  /** Splits the rail's Concept and Method panels. */
  kind: "concept" | "method";
  /** Every term that merged into this cluster (incl. `term`). The rail's chips. */
  members: string[];
  /** Funder-centrality in (0,1]. EDITABLE — this is what a slider moves. */
  centrality: number;
  /**
   * The FIXED half of the fusion weight: `weight = centrality^γ × weightFactor`. Not editable.
   *
   * Named for its ROLE in the formula, not its implementation — and naming it that way is what
   * let the FINDING's fix land without touching this type, the route or the panel. The RANKER
   * owns what this number means; the contract only promises it is the non-editable
   * multiplicand, so the client can recompute the score after a slider move.
   *
   * It USED to be `dampedIdf(corpus coverage)`, and that was the bug: corpus rarity
   * anti-correlates with topical centrality in a hierarchical domain, so a disease's own
   * mechanisms outweighed the disease (Myofibroblasts 8.44 > Fibrosis 8.00 > Scleroderma
   * 7.24) and a mechanism generalist outranked the disease specialist.
   *
   * #1676 demoted rarity to a bounded ±15% tiebreaker. A sweep then showed the band was not
   * paying for itself AT ALL — at γ=4, keeping it scores 0.6610 and deleting it scores 0.6612.
   * So it is gone, not merely bounded: corpus rarity is a real signal about the LITERATURE and
   * simply not one about TOPICALITY, and the fusion weight is a topicality claim.
   *
   * The spine now sets it to `kindPrior(kind, targetKind)` alone — a prior that boosts whichever
   * kind THIS paste is targeting. Topicality is carried entirely by `centrality^γ`. Rarity
   * survives on the wire as `corpusCoverage` (display-only, below), which is the honest place
   * for it. See `docs/2026-07-12-FINDING-idf-inverts-concept-weighting.md` §8.
   *
   * INVARIANT: whatever the engine puts here must NOT depend on `centrality` — the client
   * re-derives the weight on every slider drag, so a centrality-contaminated `weightFactor`
   * would freeze the original value into the "fixed" half and desync the sliders.
   */
  weightFactor: number;
  /**
   * DISPLAY ONLY — never a ranking input, and never read by `fusedScore`. The fraction of
   * the local corpus carrying this concept, which is what the rail's rarity badge means.
   *
   * Split out from `weightFactor` on purpose: the badge is a claim about the LITERATURE
   * ("few Weill Cornell papers cover this"), while `weightFactor` is a claim about the
   * RANKING. They coincide today only because the engine happens to derive one from the
   * other, and the finding above is the case for pulling them apart. Conflating them is
   * what made the old ·rare badge misleading — it read as "this concept is distinctive"
   * while actually meaning "this MeSH term is uncommon in PubMed".
   *
   * ABSENT when unknown — no `mesh_descriptor` row, or a coverage of exactly 0 (which is
   * 40% of descriptors; see the finding's §6 cliff). Absent is NOT zero, and the UI must
   * render no badge rather than claim "common".
   */
  corpusCoverage?: number;
  /**
   * The funder's QUALIFYING CONTEXT for this concept — their own words for what they mean by it
   * ("lysosomal processing of ADC linkers", not the bare token "lysosomes"). The canonical `term`
   * is stripped to a MeSH-resolvable noun phrase; this keeps the sense that strip discards.
   *
   * It does BOTH jobs, deliberately: the spine searches it as the free-text (BM25) query so the
   * ranking favours the sponsor's sense over everything the bare token can literally hit, and the
   * rail renders it as the "sponsor's words" line. ABSENT when the concept stood alone in the paste
   * or on the dictionary-fallback path (no LLM) — never fabricated, so the rail shows nothing rather
   * than invent a gloss. DISPLAY value only on the wire; the retrieval use happens server-side.
   */
  gloss?: string;
};

/** Per-candidate, per-concept retrieval rank (1-based) — `rank_{s,c}` in the formula.
 *  The re-rank inputs. A candidate carries one of these for EVERY concept it appeared
 *  under, however weakly. */
export type SponsorContribution = {
  /** Joins to `SponsorConcept.term`. */
  term: string;
  /** 1-based rank in that concept's `searchPeople` ranking. Lower is better. */
  rank: number;
};

/** Non-topical candidate attributes the preference nudges and status tags read.
 *  Optional because a caller may omit the hydration read; when present, every field is
 *  real (#1654). */
export type SponsorMeasures = {
  careerStage?: CareerStage | null;
  isClinician?: boolean;
  /** ED's raw person-type code (`full_time_faculty`, `postdoc`, `doctoral_student_phd`, …).
   *  The person-type facet filters on it. Sourced from the Scholar row, NOT from the
   *  People-index hit: the index coerces a null role to the literal string `"unknown"`
   *  (lib/search-index-docs.ts), and a fabricated value is worse than an absent one. */
  roleCategory?: string | null;
};

/** The scholar columns `sponsorMeasuresFrom` needs. Both engines already read Scholar for
 *  the candidate cwids, so this is extra COLUMNS on an existing query, not an extra query. */
export type SponsorMeasuresRow = {
  roleCategory: string | null;
  primaryTitle: string | null;
  hasClinicalProfile: boolean;
  appointments: { startDate: Date | null }[];
  educations: { year: number | null; degree: string | null }[];
};

/**
 * #1654 — the measures producer. Career stage reuses `careerStageBucket`, the same
 * derivation the grant matcher ranks on, so the two consoles cannot disagree about who is
 * early-career. Clinician reads `hasClinicalProfile` (derived from LDAP personTypeCodes),
 * which is the institution's own answer to "is this person a clinician" — not a guess from
 * the title string.
 */
export function sponsorMeasuresFrom(row: SponsorMeasuresRow, now: Date = new Date()): SponsorMeasures {
  return {
    careerStage: careerStageBucket(
      {
        roleCategory: row.roleCategory,
        title: row.primaryTitle,
        appointments: row.appointments,
        educations: row.educations,
      },
      now,
    ),
    isClinician: row.hasClinicalProfile,
    roleCategory: row.roleCategory,
  };
}

/**
 * #1689 — the SAME evidence the public People card renders, carried straight through from the
 * `searchPeople` hit that retrieved this candidate. ONE of these per CONCEPT the candidate
 * matched (#1696), not one per candidate.
 *
 * Deliberately the search's own `ResultEvidence`, not a sponsor-shaped copy of it. The sponsor
 * console and the public search answer the same question — *why did this scholar match?* — and
 * two independent answers to one question is how they come to disagree. The panel renders it
 * with the search's own `<EvidenceLine>`, so there is one renderer and one selection ladder.
 * Widening to per-concept keeps that property: it is the SAME payload, N times, not a second
 * shape that would need a second renderer.
 *
 * `keyPaper` carries what the LAZY representative-papers fetch needs (`/api/search/key-paper`),
 * scoped to THIS concept — so the papers a disclosure reveals are papers about the concept the
 * block is captioned with, not about the paste in general. That scoping is why the evidence has
 * to be per-concept in the first place: `keyPaper` is meaningless without knowing which concept
 * it belongs to.
 */
export type SponsorSearchEvidence = {
  /** The concept this evidence is FOR. Joins to `SponsorContribution.term` and
   *  `SponsorConcept.term` — the same representative-term key everything else in this
   *  contract joins on, so a caller can put a block under its slider. */
  term: string;
  evidence: ResultEvidence;
  /** The scholar's total publication count — the `M` in "N of M publications". */
  pubCount: number;
  keyPaper: {
    descriptorUis: string[];
    contentQuery: string;
    conceptLabel?: string;
  };
};

/** Why this candidate ranked, in the BESPOKE engine's shape. Optional — the spine does not
 *  produce it (it produces `searchEvidence` above instead, which is richer and shared with the
 *  public search). Kept because the bespoke engine, which makes one scored BM25 round-trip,
 *  DOES populate it and the panel still renders it on that path. */
export type SponsorEvidence = {
  topics?: { label: string; pubCount: number }[];
  methods?: { label: string; pubCount: number }[];
  papers?: {
    pmid: string;
    title: string;
    year: number | null;
    journal: string | null;
    /** BM25 relevance in [0,1], when the engine scored the paper. Bespoke only. */
    relevance?: number;
  }[];
};

export type SponsorCandidate = {
  cwid: string;
  name: string;
  /** Public profile slug — the card's link target. */
  profileSlug: string;
  title: string | null;
  department: string | null;
  /** Fused RRF score at the ranker's DEFAULT weights. The UI buckets it into a tier
   *  relative to the top hit and NEVER renders the raw number. Recomputed client-side by
   *  `rerankCandidates` as sliders move. */
  fusedScore: number;
  /** THE HINGE — see the module doc. Every concept this candidate appeared under. */
  contributions: SponsorContribution[];
  /** Licensable CTL technologies this researcher already holds. 0 when none. */
  technologyCount: number;
  /**
   * The scholar's headshot URL, for `HeadshotAvatar`. Same field, same producer
   * (`identityImageEndpoint(cwid)`) and same fallback as every other person surface.
   *
   * SERVER-DERIVED, and it has to be. `identityImageEndpoint` reads
   * `process.env.SCHOLARS_HEADSHOT_BASE` — an allowlisted override
   * (`scripts/release/flag-parity-allowlist.txt`) — and the panel is a `"use client"` component,
   * where a non-`NEXT_PUBLIC_` env var is `undefined`. Deriving the URL in the browser would
   * therefore silently ignore the override and hard-code the default base: the local-on /
   * deployed-off flag-parity bug, wearing a URL. So it rides the payload, computed once where
   * the env actually exists.
   *
   * OPTIONAL because absence is a real, correct state, not an unfinished one: a scholar with no
   * directory photo already renders the name-gradient fallback (the endpoint is requested with
   * `returnGenericOn404=false`), so an absent field and a 404 land in exactly the same place. A
   * test asserts both producers emit it — that, not the type, is what stops it rotting into
   * another declared-but-never-connected field.
   */
  identityImageEndpoint?: string;
  measures?: SponsorMeasures;
  evidence?: SponsorEvidence;
  /**
   * #1689/#1696 — the search's own evidence, ONE ENTRY PER CONCEPT this candidate matched.
   * Produced by the SPINE.
   *
   * An ARRAY, not a `Record<term, …>`, for three reasons. It preserves ORDER, and the order is
   * information: the spine ships the concepts STRONGEST-FIRST at default weights, so a consumer
   * that renders the list in order leads with the strongest reason without recomputing anything.
   * A `term` key is free text from an LLM, and JS object keys reorder integer-like strings to
   * the front — a concept literally named "1p19q" would silently jump the queue. And the join it
   * needs is to `contributions[]`, which is itself an array keyed by `term`; two arrays joined
   * on the same key is simpler than one array and one map.
   *
   * TWO FILTERS, both applied BEFORE the `MAX_EVIDENCE_CONCEPTS` cap:
   *   1. MATCH EVIDENCE ONLY (`isResearchMatchEvidence`). `searchPeople`'s ladder always returns
   *      something — it terminates in `{ kind: "none" }` — so an unresolved cluster comes back
   *      carrying the IDENTITY TAIL (`areas` / `concepts` / `none`), which answers "who is this
   *      person", not "why did they match". Shipping that as a block captioned with a sponsor's
   *      concept renders self-reported research areas as evidence FOR a concept nothing
   *      connected them to. Those entries are dropped, not rendered.
   *   2. STRENGTH CAP. The top `MAX_EVIDENCE_CONCEPTS` by `conceptWeight(c)/(K + rank)`.
   *
   * ABSENT — never `[]` — when nothing survives. A concept that produced no match evidence
   * contributes NO entry; it is never padded with a zero count. Absent ≠ zero.
   *
   * THE RESIDUAL, stated plainly because it does not go away: the cap is applied SERVER-SIDE at
   * DEFAULT weights, and the client re-ranks at EDITED ones. So the chips (`matchedConcepts`,
   * derived live from `contributions`) and the blocks (`matchedEvidence`, joined to what the
   * server shipped) CAN disagree once a candidate's contributions exceed the cap: slide a
   * concept up from OUTSIDE the top-3-at-default and its chip will lead the card with no block
   * beneath it, and none can be recovered client-side — the evidence was never sent.
   *
   * That is a real limit, not a bug to be argued away, and the invariant is the honest one:
   *   a chip with no block means "no block was shipped for this concept" — either it had no
   *   match evidence, or it fell below the cap at default weights — and in BOTH cases we render
   *   NOTHING rather than guess. The card under-claims; it never fabricates.
   * (An earlier draft of this doc claimed the two surfaces "cannot come to disagree". They can.
   * Fixing it for real means shipping evidence for every contribution and capping in the client,
   * which trades payload size for it; that trade has not been made.)
   */
  searchEvidence?: SponsorSearchEvidence[];
};

/**
 * A non-topical nudge extracted from the paste ("we prefer physician-scientists"). Produced
 * by `extractSponsorPreferences` (#1654).
 *
 * A DISCRIMINATED UNION, because a preference is not scoreable without its TARGET. The old
 * shape carried `measure: keyof SponsorMeasures` and nothing else, which named the field to
 * read but never what value would satisfy it — "careerStage" alone cannot tell you whether
 * the sponsor wanted juniors or seniors. Carrying the target in the type means the predicate
 * below cannot be written wrong.
 */
export type SponsorPreference = {
  label: string;
  /** The "from paste: …" provenance line. */
  evidence: string;
  /** Weight in `preferenceBoost`, in [0,1]. */
  importance: number;
} & (
  | { measure: "careerStage"; stages: CareerStage[] }
  | { measure: "isClinician" }
);

/**
 * Preference strength λ in `score × (1 + λ·prefBoost)`.
 *
 * 0.25 — a NUDGE, deliberately not a re-sort. A candidate who satisfies every stated
 * preference scores at most 25% above an identical candidate who satisfies none, so a
 * preference can lift a near-miss past a marginally-better topical match but can never haul
 * a weak match over a strong one. That ordering is the point: the sponsor's money follows
 * the science, and the preference breaks ties within it.
 *
 * It is also the blast radius. The ranking eval grades TOPICAL relevance, so any non-topical
 * boost can only cost nDCG — λ is the bound on how much. Retune it against a run of the eval,
 * not against intuition.
 */
export const PREFERENCE_LAMBDA = 0.25;

/**
 * The reference preference predicate: what fraction of the ACTIVE preferences this candidate
 * satisfies, weighted by importance. In [0,1] — the `prefBoost` the formula multiplies by λ.
 *
 * Lives in the contract, not in the panel, because two callers must agree on it: the console
 * (which re-ranks live) and the ranking eval (which has to score exactly what a user sees, or
 * it is measuring a system nobody runs). A predicate defined in the component could not be
 * called by the eval without duplicating it, and a duplicated predicate is a drifted one.
 *
 * ABSENT IS NOT ZERO. A candidate whose `measures` are missing satisfies NOTHING — she is not
 * scored as failing the preference, she is scored as not having been shown to meet it, which
 * is the same arithmetic but a different claim, and it is the honest one.
 */
export function preferenceBoost(
  candidate: SponsorCandidate,
  preferences: readonly SponsorPreference[],
): number {
  let matched = 0;
  let total = 0;
  for (const p of preferences) {
    total += p.importance;
    const m = candidate.measures;
    if (!m) continue;
    // A `switch` with a `never` default, not a ternary. The union has two arms today, so a
    // ternary's false branch narrows to `isClinician` and reads correctly — but the moment a
    // third arm is added, that false branch silently widens and scores the NEW preference as
    // a clinician preference, with no compile error. This module's header promises drift is
    // "a compile error rather than a live bug"; the ternary did not keep that promise.
    let hit: boolean;
    switch (p.measure) {
      case "careerStage":
        hit = m.careerStage != null && p.stages.includes(m.careerStage);
        break;
      case "isClinician":
        hit = m.isClinician === true;
        break;
      default: {
        const unhandled: never = p;
        void unhandled;
        hit = false;
      }
    }
    if (hit) matched += p.importance;
  }
  return total > 0 ? matched / total : 0;
}

export type SponsorMatchResponse = {
  ok: true;
  concepts: SponsorConcept[];
  candidates: SponsorCandidate[];
  /** A short handle for this search — see `sponsorAskFrom`. Absent when the paste yielded
   *  no concepts (⇒ nothing to name it after). */
  ask?: { title: string };
  /** The extractor's raw title (essence + org, no preference chips), shipped so the console
   *  can re-derive `ask` live as preferences toggle without re-fetching. Absent ⇒ the console
   *  falls back to a concept-list title. See `sponsorAskFrom`. */
  titleSummary?: string;
  preferences?: SponsorPreference[];
};

/**
 * The funder's ask, as a short handle for the results header ("Cardiac fibrosis,
 * myofibroblast differentiation · early career").
 *
 * THIS FUNCTION MAKES NO LLM CALL — it consumes one. `titleSummary` is the essence handle the
 * extractor wrote in the SAME call that read the concepts (a richer output schema, NOT a second
 * request); the thing the contract forbids is a SEPARATE title call, which — since the task
 * role's IAM grant (cdk/lib/app-stack.ts, "TaskRoleBedrockPolicy") admits only Opus and Sonnet,
 * Haiku excluded on purpose — would be a SECOND SONNET CALL, roughly doubling per-request LLM
 * spend on a route with no rate limit. When `titleSummary` is absent (dictionary fallback, a
 * paste with no org, or a failed format guard) the handle falls back to the top concepts,
 * DERIVED — costs nothing, cannot fail, cannot time out. Either way the ASSEMBLY here (the
 * preference chips, the ` · ` joins) is deterministic; only the essence rode in on the LLM.
 *
 * It used to also return `quote` — `preferences[0].evidence`, the paste snippet a preference was
 * read from. Nothing ever rendered it, and nothing needed to: the Preferences rail already shows
 * each preference's own provenance inline (`from paste: "…"`), per preference rather than only
 * the first. A produced-but-unread field is the same latent bug as a declared-but-unwritten one
 * wearing a disguise — it survives review because `git grep` finds an assignment.
 */
export function sponsorAskFrom(
  concepts: readonly SponsorConcept[],
  preferences: readonly SponsorPreference[] = [],
  titleSummary?: string,
): { title: string } | undefined {
  // Prefer the extractor's essence handle; fall back to the top concept terms, joined.
  const base =
    titleSummary?.trim() || concepts.slice(0, ASK_TITLE_CONCEPTS).map((c) => c.term).join(", ");
  if (base.length === 0) return undefined;
  const prefs = preferences.map((p) => p.label);
  return { title: [base, ...prefs].join(" · ") };
}

/** Two concepts name a search; five are a list, not a handle. */
const ASK_TITLE_CONCEPTS = 2;

/** Options for the reference scorers. `prefBoost` is injected because the UI owns the
 *  preference match predicate (the ranker ships `measures`, not verdicts). Absent ⇒ the
 *  preference term of the formula is inert, which is today's state. */
export type RerankOptions = {
  k?: number;
  /** Returns the candidate's preference boost in [0,1]. */
  prefBoost?: (candidate: SponsorCandidate) => number;
  /** Preference strength λ. Only read when `prefBoost` is supplied. */
  lambda?: number;
};

/** Fusion weight for one concept: `centrality^γ × weightFactor`. Centrality is the slider;
 *  weightFactor is the ranker's fixed multiplicand. Zeroing a slider zeroes the concept's
 *  contribution without dropping it, and γ (CENTRALITY_GAMMA) leaves that property intact —
 *  0^γ is still 0, 1^γ is still 1 — while widening the gap between a primary target and its
 *  supporting mechanisms everywhere in between.
 *
 *  γ belongs HERE and not baked into the server's `weightFactor` for a specific reason: the
 *  slider moves `centrality`, so the exponent has to be re-applied on every drag. Folding it
 *  into `weightFactor` server-side would bake in the ORIGINAL centrality and make a dragged
 *  slider compute a different weight than the server would for that same value.
 *
 *  Note what is NOT here: `corpusCoverage`. It is display-only, and keeping it out of the
 *  one function that defines the weight is what makes that guarantee checkable rather than
 *  a comment. */
export function conceptWeight(concept: SponsorConcept): number {
  return concept.centrality ** CENTRALITY_GAMMA * concept.weightFactor;
}

/** Term → fusion weight, for a whole concept set. */
export function conceptWeights(concepts: readonly SponsorConcept[]): Map<string, number> {
  return new Map(concepts.map((c) => [c.term, conceptWeight(c)]));
}

/**
 * The reference score (pivot handoff §4):
 *
 *     score(s) = Σ_c  weight(c) / (K + rank_{s,c})   × (1 + λ·prefBoost(s))
 *
 * PURE — this is what makes the live re-rank possible: given the response, a slider move
 * is arithmetic over data already in the browser, not a round-trip. A contribution whose
 * concept is absent from `weightByTerm` contributes 0 (it was dropped from the rail), and
 * a concept a candidate never appeared under contributes 0 by having no contribution row.
 */
export function fusedScore(
  candidate: SponsorCandidate,
  weightByTerm: ReadonlyMap<string, number>,
  opts: RerankOptions = {},
): number {
  const k = opts.k ?? DEFAULT_K;
  let score = 0;
  for (const { term, rank } of candidate.contributions) {
    score += (weightByTerm.get(term) ?? 0) / (k + rank);
  }
  if (!opts.prefBoost) return score;
  return score * (1 + (opts.lambda ?? 1) * opts.prefBoost(candidate));
}

/**
 * Re-rank the ALREADY-FETCHED candidates under an edited concept set. No network.
 *
 * At the ranker's default weights this reproduces the order the server sent — the
 * property the contract test pins, and the reason the server and client must share
 * `DEFAULT_K`. Ties break on the incoming order, which (since the server ships candidates
 * in fused order) preserves the ranker's own stable first-seen tie-break.
 *
 * An EMPTY concept set is a no-op, not a wipe. An engine with no concept decomposition
 * (the bespoke ranker) ships `concepts: []` and `contributions: []`, carrying its real
 * score in `fusedScore`. Re-ranking that by the formula would sum an empty contributions
 * list to 0 for every candidate and OVERWRITE the server's score with it — leaving the
 * order intact (every candidate ties, and ties keep the incoming order) while silently
 * flattening every derived `fitTier` to "weak", top hit included. There is nothing to
 * re-rank by, so we return what we were given.
 */
export function rerankCandidates(
  candidates: readonly SponsorCandidate[],
  concepts: readonly SponsorConcept[],
  opts: RerankOptions = {},
): SponsorCandidate[] {
  if (concepts.length === 0) {
    // No concept decomposition (the bespoke engine): there is nothing to re-rank BY, and the
    // real score already lives in `fusedScore` — see the note above on why re-deriving it
    // here would flatten every tier to "weak".
    //
    // But a preference is not a concept, and #1654's nudge must not be silently inert on an
    // engine just because that engine ships no concepts. Scale the score the server DID send,
    // which is the same `× (1 + λ·prefBoost)` the decomposed path applies — and re-sort, since
    // the boost can legitimately reorder.
    if (!opts.prefBoost) return [...candidates];
    const lambda = opts.lambda ?? 1;
    return candidates
      .map((candidate, index) => ({
        candidate,
        index,
        score: candidate.fusedScore * (1 + lambda * opts.prefBoost!(candidate)),
      }))
      .sort((a, b) => b.score - a.score || a.index - b.index)
      .map(({ candidate, score }) => ({ ...candidate, fusedScore: score }));
  }
  const weights = conceptWeights(concepts);
  return candidates
    .map((candidate, index) => ({
      candidate,
      index,
      score: fusedScore(candidate, weights, opts),
    }))
    .sort((a, b) => b.score - a.score || a.index - b.index)
    .map(({ candidate, score }) => ({ ...candidate, fusedScore: score }));
}

/**
 * The concepts a candidate actually matched, strongest first — the card's chips. DERIVED
 * (not wired) so the chips re-order live as sliders move: a concept slid to near-zero
 * drops down the chip list without a re-query.
 *
 * Strength is the concept's own contribution to this candidate's score — the same
 * `weight/(K + rank)` term the fusion sums — so a chip's prominence means exactly what it
 * means in the ranking. Concepts with zero weight are omitted (they contribute nothing).
 */
export function matchedConcepts(
  candidate: SponsorCandidate,
  concepts: readonly SponsorConcept[],
  opts: RerankOptions = {},
): { concept: SponsorConcept; strength: number }[] {
  const k = opts.k ?? DEFAULT_K;
  const byTerm = new Map(concepts.map((c) => [c.term, c]));
  return candidate.contributions
    .flatMap(({ term, rank }) => {
      const concept = byTerm.get(term);
      if (!concept) return [];
      const strength = conceptWeight(concept) / (k + rank);
      return strength > 0 ? [{ concept, strength }] : [];
    })
    .sort((a, b) => b.strength - a.strength);
}

/**
 * The evidence blocks to render on a candidate's card (#1696) — the per-concept evidence the
 * spine shipped, joined to the concepts the candidate ACTUALLY matched under the CURRENT
 * weights, and in the order those concepts currently rank.
 *
 * Derived from `matchedConcepts` rather than from the wire order, so the blocks track the live
 * weighting exactly as the chips do. Mute a concept and it stops being a reason this person
 * ranked — so its chip goes, and its evidence block goes with it. A block still captioned
 * "Fibrosis" under a slider dragged to zero would be the card contradicting the ranking beside
 * it, which is the failure `matchedConcepts` was derived-not-wired to avoid.
 *
 * The blocks are therefore a SUBSET of the chips, and can be a strict one. The server decides
 * WHICH concepts have evidence here at all: it drops the identity tail and caps at
 * `MAX_EVIDENCE_CONCEPTS` by strength at DEFAULT weights (see `SponsorCandidate.searchEvidence`
 * for both, and for the residual this leaves). This function only decides which of what it was
 * SENT a given weighting still stands behind, and in what order — it cannot conjure a block the
 * server did not ship, and does not try to.
 *
 * So: chip without block is EXPECTED and means "nothing was shipped for this concept" (no match
 * evidence, or below the cap at default weights). Block without chip is impossible — a block
 * requires a matched concept. A concept with no shipped evidence yields NO entry (absent ≠ an
 * empty block), and a candidate with no `searchEvidence` yields []. Neither is padded.
 */
export function matchedEvidence(
  candidate: SponsorCandidate,
  concepts: readonly SponsorConcept[],
  opts: RerankOptions = {},
): { concept: SponsorConcept; evidence: SponsorSearchEvidence }[] {
  if (!candidate.searchEvidence || candidate.searchEvidence.length === 0) return [];
  const byTerm = new Map(candidate.searchEvidence.map((e) => [e.term, e]));
  return matchedConcepts(candidate, concepts, opts).flatMap(({ concept }) => {
    const evidence = byTerm.get(concept.term);
    return evidence ? [{ concept, evidence }] : [];
  });
}

/**
 * What the sponsor asked for, against what this candidate has — EVERY asked concept, including
 * the ones they have nothing for. That complement is the point: `matchedConcepts` can only tell
 * you what a person matched, so nothing on the card has ever been able to say what they LACK,
 * and a reader cannot tell "covered 4 of 4" from "covered 4 of 8" by looking at four chips.
 *
 * Three states, and the middle one is the one to be careful about:
 *   - `evidence` — the candidate ranked under this concept AND the server shipped an evidence
 *                  block for it, so `matchedEvidence` renders one. Defined as the conjunction on
 *                  purpose: this state means "there is a block below", and it stays true by
 *                  construction rather than by a comment claiming it.
 *   - `ranked`   — the candidate ranked under it, but NO block was shipped. This is NOT "partial
 *                  evidence" and must never be rendered as a weaker shade of found. The spine
 *                  caps evidence at `MAX_EVIDENCE_CONCEPTS` by strength AT DEFAULT WEIGHTS, so an
 *                  officer who slides the 4th concept to the top produces exactly this: a chip, a
 *                  segment, and no block — and no client can conjure one (see `searchEvidence`).
 *   - `none`     — the candidate did not rank under it at all. The gap. Nothing rendered this.
 *
 * Zero-weight concepts are ABSENT, not `none`: an officer who muted a concept has said they do
 * not care about it, and is not owed a report that this person lacks it. Ordered by weight, so
 * the strip reads as the ask itself — widest first — and re-orders live as the sliders move.
 */
export type ConceptCoverage = {
  concept: SponsorConcept;
  weight: number;
  state: "evidence" | "ranked" | "none";
};

export function conceptCoverage(
  candidate: SponsorCandidate,
  concepts: readonly SponsorConcept[],
): ConceptCoverage[] {
  // Absent, never `[]` — gate on the term's PRESENCE, not on the array's truthiness.
  const withEvidence = new Set((candidate.searchEvidence ?? []).map((e) => e.term));
  const ranked = new Set(candidate.contributions.map((c) => c.term));
  return concepts
    .map((concept) => ({
      concept,
      weight: conceptWeight(concept),
      state: !ranked.has(concept.term)
        ? ("none" as const)
        : withEvidence.has(concept.term)
          ? ("evidence" as const)
          : ("ranked" as const),
    }))
    .filter((s) => s.weight > 0)
    .sort((a, b) => b.weight - a.weight);
}

/**
 * Bucket a candidate's fused score into a fit tier, RELATIVE to the top candidate's — the
 * raw fused number is never rendered (it is a query-scaled RRF sum and means nothing to a
 * reader on its own). A non-positive top score means nothing matched: everything is weak.
 */
export function fitTier(score: number, topScore: number): SponsorFitTier {
  if (topScore <= 0) return "weak";
  const share = score / topScore;
  if (share >= TIER_STRONG) return "strong";
  if (share >= TIER_GOOD) return "good";
  return "weak";
}

/** A concept is "rare" when its corpus coverage is at most this fraction of the most-covered
 *  concept in the SAME ask — i.e. roughly an order of magnitude scarcer than its peers. */
export const RARE_COVERAGE_RATIO = 0.1;

/**
 * The terms to badge as rare, judged RELATIVE to the other concepts in the same ask.
 *
 * Relative, because an absolute cutoff would badge everything: every MeSH concept is rare at
 * corpus scale. The seven concepts of the scleroderma ask span 4.9e-5 to 1.5e-3 — all "rare"
 * on any absolute threshold, so an absolute badge carries no information. What an officer can
 * actually act on is which concepts in THIS ask are the scarce ones locally, and that is a
 * within-ask comparison.
 *
 * A concept with no `corpusCoverage` is never badged (unknown ≠ common — see the field doc),
 * and it is excluded from the comparison rather than counted as zero. Fewer than two known
 * coverages means there is nothing to be relative TO, so nothing is badged.
 *
 * This reads `corpusCoverage` and nothing else. It has no access to `weightFactor`, which is
 * the structural guarantee that the badge cannot drift back into being a claim about ranking.
 *
 * DECIDED 2026-07-14 — KEEP IT AS IS. It fires on 6 of 8 concepts of the ADC ask, which was
 * raised as a defect: a badge on three-quarters of the rail is said to carry no information.
 * The badge is nonetheless ACCURATE, the reading was reviewed, and the answer is that it stays.
 * Do not "fix" this by tightening `RARE_COVERAGE_RATIO` on the evidence of a single paste, and
 * do not invert it to badge the COMMON terms — "common" is unsayable here, because ~40% of
 * descriptors have no coverage row and absent ≠ zero, so "not rare" cannot be rendered as
 * "common" without lying about the unknowns. Tightening the ratio at all requires sampling
 * several real asks first, not one.
 *
 * Nor is the badge "already gone" — a prior handoff asserted that, and it was wrong. Rarity was
 * deleted from the FUSION (#1698); this badge is display-only and has been rendering all along.
 * `git grep rareTerms` before you believe otherwise.
 */
export function rareTerms(concepts: readonly SponsorConcept[]): Set<string> {
  const known = concepts.filter(
    (c): c is SponsorConcept & { corpusCoverage: number } =>
      typeof c.corpusCoverage === "number" && c.corpusCoverage > 0,
  );
  if (known.length < 2) return new Set();
  const maxCoverage = Math.max(...known.map((c) => c.corpusCoverage));
  return new Set(
    known
      .filter((c) => c.corpusCoverage <= maxCoverage * RARE_COVERAGE_RATIO)
      .map((c) => c.term),
  );
}

/**
 * A candidate is a RESULT only if the spine shipped at least one research-match evidence block
 * for it. `searchEvidence` is ALREADY filtered to match evidence (`isResearchMatchEvidence` drops
 * the identity tail — self-reported areas, concept hints, `none`), so an empty/absent array means
 * the scholar ranked into some concept's `searchPeople` top-100 on an identity-tail hit and matched
 * NOTHING real. A card with an empty evidence strip and a full "no evidence" list is noise, not a
 * result; the console excludes these entirely rather than collapsing them under the floor.
 */
export function hasMatchEvidence(candidate: SponsorCandidate): boolean {
  return (candidate.searchEvidence?.length ?? 0) > 0;
}

/** How one evidence block landed: a STRUCTURED signal or a BARE free-text hit. */
export type EvidenceProvenance = "tagged" | "keyword";

/**
 * The provenance of a per-concept evidence block — the honest, cheap distinction the display can
 * draw TODAY: did the hit land via a structured signal (a MeSH subject tag, a curated method /
 * clinical / topic match) or via bare free text (a publication `mention`, a bio sentence)?
 *
 * `keyword` is the false-positive risk an officer must be able to see — a concept's bare token
 * matching a paper that has nothing to do with the sponsor's sense ("patient-derived xenografts"
 * matched, the sense did not). It marks HOW the hit landed, NOT that it landed in the sponsor's
 * SENSE: a paper MeSH-tagged `Lysosomes` reads `tagged` even when it is an aluminum-ion probe that
 * merely labels lysosomes. Separating that from lysosomal-ADC processing needs the concept's gloss
 * and a semantic match, not this flag — so the chip never claims "matched in context".
 *
 * `null` for kinds that carry no such signal. The spine already filters the identity tail via
 * `isResearchMatchEvidence`, so a `null` here is a total-function backstop, not a live path.
 */
export function evidenceProvenance(evidence: ResultEvidence): EvidenceProvenance | null {
  switch (evidence.kind) {
    case "publications":
      // `tagged` = subject heading, `concept` = MeSH-expansion variant — both structured.
      // `mention` = the literal query hit free text — the bare-keyword signal.
      return evidence.strength === "mention" ? "keyword" : "tagged";
    case "method":
    case "clinical":
    case "topic":
      return "tagged";
    case "selfDescription":
      // A sentence from the scholar's own overview — a real hit, but self-reported prose, not a
      // subject tag. Honest to group it with the bare-text signal rather than the structured one.
      return "keyword";
    default:
      return null;
  }
}

/**
 * The per-concept MATCHED publication count — the "N" in "N of M publications" — for a demoted
 * supporting row that does not mount an `EvidenceLine`.
 *
 * NOT `SponsorSearchEvidence.pubCount`, which is the scholar's TOTAL (the "M") and is therefore the
 * SAME for every concept on the card. Rendering that as a per-concept count is a lie a reader spots
 * immediately: "drug resistance · 480 pubs" beside "480" everywhere else. The matched count lives on
 * the evidence's own `count` (the count-bearing kinds set it). `null` for kinds that carry no such
 * number (clinical / selfDescription) — the caller renders nothing rather than fall back to the
 * total, which is the very number that was wrong.
 */
export function evidenceMatchCount(evidence: ResultEvidence): number | null {
  switch (evidence.kind) {
    case "publications":
    case "method":
    case "topic":
      return typeof evidence.count === "number" ? evidence.count : null;
    default:
      return null;
  }
}

/**
 * The most-recent evidence year we ALREADY HOLD for a candidate — D8's compact-row "latest YYYY".
 *
 * INTERIM SOURCE, and deliberately narrow: only the bespoke engine's `evidence.papers` carries a
 * year up front. The production SPINE path ships `searchEvidence`, whose artifact (and its year) is
 * lazy-fetched on view — so this returns `null` there, and the compact row renders no year until D1
 * surfaces a per-scholar most-recent year in the payload. Point this at that field when it lands;
 * nothing else on the row should need to change. (D8's stale colour-flag is likewise gated on D1's
 * recency threshold — the year renders neutral until then.)
 */
export function latestEvidenceYear(candidate: SponsorCandidate): number | null {
  const years = (candidate.evidence?.papers ?? [])
    .map((p) => p.year)
    .filter((y): y is number => typeof y === "number");
  return years.length > 0 ? Math.max(...years) : null;
}
