// Pure formatter: CloudWatch alarm payload -> Adaptive Card envelope POSTed
// to a Power Automate "When an HTTP request is received" workflow. Decoupled
// from network + Secrets Manager so the formatter is independently testable.
//
// TextBlock.text is rendered as plain text by default by the Teams Adaptive
// Card host; markdown is opt-in via the explicit `markdown` property on
// hosts that support it. We do not enable it. CloudWatch's NewStateReason
// text is operator-controlled (it's generated by CloudWatch from the metric
// expression) rather than user-controlled, but the no-markdown default
// removes one whole class of injection vector regardless.

/** Schema of the inner `Message` JSON CloudWatch alarms publish to SNS. */
export interface CloudWatchAlarmPayload {
  readonly AlarmName: string;
  readonly AlarmDescription?: string;
  readonly NewStateValue: "ALARM" | "OK" | "INSUFFICIENT_DATA" | string;
  readonly NewStateReason?: string;
  readonly StateChangeTime?: string;
  readonly Region?: string;
  readonly AWSAccountId?: string;
}

/**
 * Severity tier assigned by the relay from the originating SNS topic. P1
 * ("page") posts to the primary on-call Teams channel; P2 ("warn") posts to a
 * separate, quieter channel (data-freshness, reconciler, and resource-pressure
 * signals). Rendered as a card fact so the tier is visible even if a P2 alert
 * falls back to the primary channel.
 */
export type AlertSeverity = "page" | "warn";

/**
 * Schema of the custom JSON the EtlStack Step Functions publish to the
 * `etl-failures-<env>` topic — the per-step failure Catch (`NotifyEd` etc.)
 * and the annual approval gate. Distinct from {@link CloudWatchAlarmPayload}:
 * the ETL status/cadence CloudWatch alarms ALSO publish to that topic via an
 * SnsAction, but those carry the alarm shape and still flow through
 * {@link buildAdaptiveCard}. The handler discriminates on the presence of
 * `AlarmName` ({@link isCloudWatchAlarmPayload}).
 */
export interface EtlEventPayload {
  readonly env?: string;
  readonly step?: string;
  readonly action?: string;
  readonly stateMachine?: string;
  readonly execution?: string;
  readonly error?: unknown;
  readonly runbook?: string;
}

/** Adaptive Card envelope shape accepted by the Teams Workflows webhook. */
export interface AdaptiveCardEnvelope {
  readonly type: "message";
  readonly attachments: ReadonlyArray<{
    readonly contentType: "application/vnd.microsoft.card.adaptive";
    readonly content: Record<string, unknown>;
  }>;
}

/** Truncate-with-ellipsis cap on Reason text. Teams flattens long facts. */
const REASON_MAX_CHARS = 1024;

/** Adaptive Card spec version we tested with. Pinned per SPEC § Risks #2. */
const ADAPTIVE_CARD_VERSION = "1.5";

/** State -> emoji map. Handler constant, not configurable. */
const STATE_EMOJI: Readonly<Record<string, string>> = {
  ALARM: "\u{1F6A8}",
  OK: "\u{2705}",
  INSUFFICIENT_DATA: "\u{2753}",
};

/** Fallback emoji for any future state CloudWatch might invent. */
const UNKNOWN_STATE_EMOJI = "\u{2753}";

function truncate(s: string, max: number): string {
  if (s.length <= max) return s;
  return s.slice(0, max - 1) + "\u{2026}";
}

function reasonFact(reason: string | undefined): string {
  if (reason === undefined || reason.length === 0) {
    return "(no reason provided)";
  }
  return truncate(reason, REASON_MAX_CHARS);
}

function cloudwatchConsoleUrl(alarmName: string, region: string): string {
  const encoded = encodeURIComponent(alarmName);
  return `https://${region}.console.aws.amazon.com/cloudwatch/home?region=${region}#alarmsV2:alarm/${encoded}`;
}

/**
 * Console deep-link to the reliability dashboard for the alarm's env, derived
 * from the `-prod` / `-staging` suffix on the alarm name (every SPS alarm
 * carries the env literal -- Footgun #4). Returns `undefined` when the env is
 * not recognisable, so the action is omitted rather than guessed. The first
 * thing an operator wants after the alarm name is the at-a-glance board, not
 * the single-metric alarm page.
 */
function reliabilityDashboardUrl(
  alarmName: string,
  region: string,
): string | undefined {
  const env = alarmName.endsWith("-prod")
    ? "prod"
    : alarmName.endsWith("-staging")
      ? "staging"
      : undefined;
  if (env === undefined) return undefined;
  return `https://${region}.console.aws.amazon.com/cloudwatch/home?region=${region}#dashboards:name=sps-reliability-${env}`;
}

/** Human-readable severity label for the card fact. */
function severityLabel(severity: AlertSeverity): string {
  return severity === "warn" ? "P2 (warn)" : "P1 (page)";
}

export function buildAdaptiveCard(
  alarm: CloudWatchAlarmPayload,
  severity?: AlertSeverity,
): AdaptiveCardEnvelope {
  const region = alarm.Region ?? "us-east-1";
  const emoji = STATE_EMOJI[alarm.NewStateValue] ?? UNKNOWN_STATE_EMOJI;
  const when = alarm.StateChangeTime ?? "(unknown)";

  // Facts are looked up by title (order-independent) on the receiving side.
  // State first, then severity + description (the actionable context, incl.
  // the runbook pointer baked into AlarmDescription), then the raw reason.
  const facts: Array<{ title: string; value: string }> = [
    { title: "State", value: alarm.NewStateValue },
  ];
  if (severity !== undefined) {
    facts.push({ title: "Severity", value: severityLabel(severity) });
  }
  if (
    alarm.AlarmDescription !== undefined &&
    alarm.AlarmDescription.length > 0
  ) {
    facts.push({
      title: "Description",
      value: truncate(alarm.AlarmDescription, REASON_MAX_CHARS),
    });
  }
  facts.push({ title: "Reason", value: reasonFact(alarm.NewStateReason) });
  facts.push({ title: "Region", value: region });
  facts.push({ title: "When", value: when });

  // CloudWatch alarm page stays first (actions[0]); the reliability dashboard
  // is the natural second click and is added only when the env is known.
  const actions: Array<{ type: string; title: string; url: string }> = [
    {
      type: "Action.OpenUrl",
      title: "View in CloudWatch",
      url: cloudwatchConsoleUrl(alarm.AlarmName, region),
    },
  ];
  const dashboardUrl = reliabilityDashboardUrl(alarm.AlarmName, region);
  if (dashboardUrl !== undefined) {
    actions.push({
      type: "Action.OpenUrl",
      title: "View reliability dashboard",
      url: dashboardUrl,
    });
  }

  return {
    type: "message",
    attachments: [
      {
        contentType: "application/vnd.microsoft.card.adaptive",
        content: {
          $schema: "http://adaptivecards.io/schemas/adaptive-card.json",
          type: "AdaptiveCard",
          version: ADAPTIVE_CARD_VERSION,
          body: [
            {
              type: "TextBlock",
              text: `${emoji} ${alarm.AlarmName}`,
              weight: "Bolder",
              size: "Medium",
              wrap: true,
            },
            {
              type: "FactSet",
              facts,
            },
          ],
          actions,
        },
      },
    ],
  };
}

/**
 * Discriminator for the two payload shapes the relay receives on the
 * etl-failures topic. CloudWatch alarms always carry a string `AlarmName`;
 * the ETL Step Functions custom payloads never do.
 */
export function isCloudWatchAlarmPayload(
  p: unknown,
): p is CloudWatchAlarmPayload {
  return (
    typeof p === "object" &&
    p !== null &&
    typeof (p as Record<string, unknown>).AlarmName === "string"
  );
}

/** Render `error` (a States error object or a string) as one safe fact line. */
function errorFact(error: unknown): string {
  if (error === undefined || error === null) return "(none)";
  if (typeof error === "string") {
    return error.length === 0 ? "(empty)" : truncate(error, REASON_MAX_CHARS);
  }
  try {
    return truncate(JSON.stringify(error), REASON_MAX_CHARS);
  } catch {
    return "(unserializable)";
  }
}

function stepFunctionsConsoleUrl(region: string): string {
  return `https://${region}.console.aws.amazon.com/states/home?region=${region}#/statemachines`;
}

/**
 * Card for an ETL Step Functions event (per-step failure or approval gate).
 * Same no-markdown, truncated, injection-safe posture as the alarm card. Only
 * the fields present on the payload are rendered, so it degrades cleanly as
 * the publisher's message shape evolves.
 */
export function buildEtlCard(payload: EtlEventPayload): AdaptiveCardEnvelope {
  const region = "us-east-1";
  const what = payload.step ?? payload.action ?? "event";
  const env = payload.env ?? "(unknown)";

  const facts: Array<{ title: string; value: string }> = [
    { title: "Env", value: env },
    { title: "Step", value: what },
  ];
  if (payload.stateMachine !== undefined) {
    facts.push({ title: "State machine", value: payload.stateMachine });
  }
  if (payload.execution !== undefined) {
    facts.push({ title: "Execution", value: payload.execution });
  }
  facts.push({ title: "Error", value: errorFact(payload.error) });
  if (payload.runbook !== undefined) {
    facts.push({ title: "Runbook", value: truncate(payload.runbook, REASON_MAX_CHARS) });
  }

  return {
    type: "message",
    attachments: [
      {
        contentType: "application/vnd.microsoft.card.adaptive",
        content: {
          $schema: "http://adaptivecards.io/schemas/adaptive-card.json",
          type: "AdaptiveCard",
          version: ADAPTIVE_CARD_VERSION,
          body: [
            {
              type: "TextBlock",
              text: `\u{1F6A8} SPS ETL ${env} \u{2014} ${what}`,
              weight: "Bolder",
              size: "Medium",
              wrap: true,
            },
            { type: "FactSet", facts },
          ],
          actions: [
            {
              type: "Action.OpenUrl",
              title: "View in Step Functions",
              url: stepFunctionsConsoleUrl(region),
            },
          ],
        },
      },
    ],
  };
}
