// Pure formatter: CloudWatch alarm payload -> Adaptive Card envelope POSTed
// to a Power Automate "When an HTTP request is received" workflow. Decoupled
// from network + Secrets Manager so the formatter is independently testable.
//
// TextBlock.text is rendered as plain text by default by the Teams Adaptive
// Card host; markdown is opt-in via the explicit `markdown` property on
// hosts that support it. We do not enable it. CloudWatch's NewStateReason
// text is operator-controlled (it's generated by CloudWatch from the metric
// expression) rather than user-controlled, but the no-markdown default
// removes one whole class of injection vector regardless.

/** Schema of the inner `Message` JSON CloudWatch alarms publish to SNS. */
export interface CloudWatchAlarmPayload {
  readonly AlarmName: string;
  readonly AlarmDescription?: string;
  readonly NewStateValue: "ALARM" | "OK" | "INSUFFICIENT_DATA" | string;
  readonly NewStateReason?: string;
  readonly StateChangeTime?: string;
  readonly Region?: string;
  readonly AWSAccountId?: string;
}

/** Adaptive Card envelope shape accepted by the Teams Workflows webhook. */
export interface AdaptiveCardEnvelope {
  readonly type: "message";
  readonly attachments: ReadonlyArray<{
    readonly contentType: "application/vnd.microsoft.card.adaptive";
    readonly content: Record<string, unknown>;
  }>;
}

/** Truncate-with-ellipsis cap on Reason text. Teams flattens long facts. */
const REASON_MAX_CHARS = 1024;

/** Adaptive Card spec version we tested with. Pinned per SPEC § Risks #2. */
const ADAPTIVE_CARD_VERSION = "1.5";

/** State -> emoji map. Handler constant, not configurable. */
const STATE_EMOJI: Readonly<Record<string, string>> = {
  ALARM: "\u{1F6A8}",
  OK: "\u{2705}",
  INSUFFICIENT_DATA: "\u{2753}",
};

/** Fallback emoji for any future state CloudWatch might invent. */
const UNKNOWN_STATE_EMOJI = "\u{2753}";

function truncate(s: string, max: number): string {
  if (s.length <= max) return s;
  return s.slice(0, max - 1) + "\u{2026}";
}

function reasonFact(reason: string | undefined): string {
  if (reason === undefined || reason.length === 0) {
    return "(no reason provided)";
  }
  return truncate(reason, REASON_MAX_CHARS);
}

function cloudwatchConsoleUrl(alarmName: string, region: string): string {
  const encoded = encodeURIComponent(alarmName);
  return `https://${region}.console.aws.amazon.com/cloudwatch/home?region=${region}#alarmsV2:alarm/${encoded}`;
}

export function buildAdaptiveCard(
  alarm: CloudWatchAlarmPayload,
): AdaptiveCardEnvelope {
  const region = alarm.Region ?? "us-east-1";
  const emoji = STATE_EMOJI[alarm.NewStateValue] ?? UNKNOWN_STATE_EMOJI;
  const when = alarm.StateChangeTime ?? "(unknown)";

  return {
    type: "message",
    attachments: [
      {
        contentType: "application/vnd.microsoft.card.adaptive",
        content: {
          $schema: "http://adaptivecards.io/schemas/adaptive-card.json",
          type: "AdaptiveCard",
          version: ADAPTIVE_CARD_VERSION,
          body: [
            {
              type: "TextBlock",
              text: `${emoji} ${alarm.AlarmName}`,
              weight: "Bolder",
              size: "Medium",
              wrap: true,
            },
            {
              type: "FactSet",
              facts: [
                { title: "State", value: alarm.NewStateValue },
                { title: "Reason", value: reasonFact(alarm.NewStateReason) },
                { title: "Region", value: region },
                { title: "When", value: when },
              ],
            },
          ],
          actions: [
            {
              type: "Action.OpenUrl",
              title: "View in CloudWatch",
              url: cloudwatchConsoleUrl(alarm.AlarmName, region),
            },
          ],
        },
      },
    ],
  };
}
