/**
 * Hero search "Try:" suggestion pool.
 *
 * 200 query strings spanning the data model: every department, every parent
 * research topic, and a randomized cross-section of subtopics. The home page
 * server-renders a small random sample from this pool on each request, so
 * what visitors see rotates every page load.
 *
 * Strings are real entity names from the live catalog (depts, topics,
 * subtopics). Each one, when typed into the autocomplete or routed to
 * /search, surfaces a meaningful entity-aware result.
 *
 * Add new entries by category. Avoid PII (individual scholar names) — those
 * are discoverable through the autocomplete itself.
 */

const DEPARTMENTS = [
  "Medicine",
  "Psychiatry",
  "Pediatrics",
  "Radiology",
  "Surgery",
  "Anesthesiology",
  "Obstetrics and Gynecology",
  "Emergency Medicine",
  "Pathology and Laboratory Medicine",
  "Orthopaedic Surgery",
  "Neurology",
  "Ophthalmology",
  "Population Health Sciences",
  "Urology",
  "Dermatology",
  "Otolaryngology Head and Neck Surgery",
  "Brain and Mind Research",
  "Rehabilitation Medicine",
  "Neurological Surgery",
  "Cardiothoracic Surgery",
  "Biochemistry and Biophysics",
  "Systems and Computational Biomedicine",
  "Pharmacology",
  "Microbiology and Immunology",
  "Radiation Oncology",
  "Genetic Medicine",
  "Cell and Developmental Biology",
  "Reproductive Medicine",
  "Library",
];

const TOPICS = [
  "Aging & Geroscience",
  "Autoimmune & Rheumatologic Disease",
  "Biochemistry & Biophysics",
  "Bioethics, Medical Humanities & Clinician Wellbeing",
  "Biomedical Engineering",
  "Biomedical Informatics",
  "Biostatistics & Quantitative Health Sciences",
  "Breast Cancer",
  "Cancer Biology (General)",
  "Cardiovascular Disease",
  "Cell & Molecular Biology",
  "Dermatology & Skin Disease",
  "Developmental Biology",
  "Digital Health & Telemedicine",
  "Drug Discovery & Pharmacology",
  "Emergency & Critical Care Medicine",
  "Environmental & Planetary Health",
  "Epidemiology & Population Health",
  "Gastroenterology, Hepatology & Pancreatic Disease",
  "Gene & Cell Therapy",
  "Genetics, Genomics & Precision Medicine",
  "Gastrointestinal Cancer",
  "Global & Public Health",
  "Gynecologic Oncology",
  "Health Economics",
  "Health Equity & Social Determinants of Health",
  "Health Services Research & Health Policy",
  "Hematology",
  "Immunology & Inflammation",
  "Implementation Science",
  "Infectious Disease & Host Defense",
  "Lung Cancer",
  "Maternal & Child Health",
  "Medical Education & Healthcare Workforce",
  "Melanoma & Skin Cancer",
  "Mental Health & Psychiatry",
  "Metabolic & Endocrine Disease",
  "Microbiome Research",
  "Musculoskeletal & Orthopedic Medicine",
  "Nephrology & Renal Disease",
  "Neuro-Oncology",
  "Neurodegenerative Disease",
  "Neuroscience & Neurology",
  "Nutrition & Metabolism",
  "Ophthalmology & Vision Science",
  "Oral & Craniofacial Health",
  "Otolaryngology & Head and Neck Medicine",
  "Pain Management & Anesthesiology",
  "Palliative & End-of-Life Care",
  "Pathology & Laboratory Medicine",
  "Pediatrics & Neonatology",
  "Primary Care & General Internal Medicine",
  "Prostate & Urologic Cancer",
  "Pulmonary & Critical Care Medicine",
  "Radiology, Medical Imaging & Medical Physics",
  "Rehabilitation & Disability Medicine",
  "Research Infrastructure & Scientific Workforce",
  "Single-Cell & Spatial Biology",
  "Sleep Medicine & Circadian Biology",
  "Stem Cell & Regenerative Medicine",
  "Substance Use & Addiction Medicine",
  "Surgery & Perioperative Medicine",
  "Systems Biology",
  "Translational & Clinical Science",
  "Transplantation Medicine",
  "Urology & Men's Health",
  "Women's Health & Reproductive Medicine",
];

const SUBTOPICS = [
  "Bone Cell Signaling & Differentiation",
  "Clinical Trial Recruitment & Participant Engagement",
  "Pancreatic Beta Cell Biology & Insulin Secretion",
  "Advanced MRI Reconstruction & Quantitative Mapping",
  "Hepatitis C Care for People Who Inject Drugs",
  "Cancer Screening & Survivorship Care",
  "Extracellular Vesicles & Cancer Metastasis",
  "Neoadjuvant Immunotherapy & Chemoradiation",
  "Breast Cancer Survivorship & Quality of Life",
  "AI-Based Skin Lesion Detection",
  "Fetal Alcohol Spectrum Disorders & Comorbidities",
  "Adrenal & Parathyroid Disorders",
  "COVID-19 Therapeutics, Vaccines & Epidemiology",
  "Preclinical Models & Novel Drug Delivery",
  "MRI-Guided Biopsy & Cancer Detection",
  "Checkpoint Inhibitor Outcomes in Melanoma",
  "Surgical Outcomes & Perioperative Management",
  "Head & Neck Reconstruction & Microsurgery",
  "Medication Adherence, Deprescribing & Polypharmacy",
  "Opioid Use Disorder in Emergency Settings",
  "High-Capacity Cloning Vector Engineering",
  "Opioid Use Disorders & Drug Policy",
  "Hematologic Malignancy Genomics",
  "Brain Organoids & Neuropsychiatric Disease Modeling",
  "Deep Learning for Medical Imaging",
  "Integrative Medicine in Palliative Care",
  "Spine Implant Economics & Opioid Prescribing",
  "Pulmonary Embolism & Venous Thromboembolism",
  "Epigenetic Aging & Clonal Hematopoiesis",
  "Metabolomics & Metabolic Profiling",
  "Heart Failure & Geriatric Cardiology",
  "Cancer Rehabilitation & Neuro-Oncology Outcomes",
  "Economic Burden of Disease & Mortality",
  "Maternal Infections & Perinatal Outcomes",
  "Hematopoietic Cell Transplantation Outcomes",
  "Endothelial Biology & Vascular Remodeling",
  "Synaptic Vesicle Biology & Neurotransmission",
  "Neurosurgical Education & Simulation Technology",
  "Nursing Home & Long-Term Care Economics",
  "Survival Analysis & Longitudinal Methods",
  "Post-Acute COVID-19 & Long COVID Rehabilitation",
  "Neuro-Oncology Rehabilitation & Outcomes",
  "Head & Neck Surgery with Thyroid Procedures",
  "Transcatheter Structural Heart Interventions",
  "Dementia Caregiving & Family Support",
  "Residency & Fellowship Program Director Demographics",
  "ML for Radiological Diagnosis & Quantification",
  "Cancer Stem Cells & Lineage Plasticity",
  "Heart Failure Home Care & Self-Management",
  "Elder Mistreatment Detection & Clinical Response",
  "Telemedicine & AR Remote Surgical Support",
  "Immunotherapy Toxicity & Inflammatory Biomarkers",
  "Metabolic & Synaptic Mechanisms in Parkinson's",
  "Heat, Climate Change & Environmental Health",
  "GWAS & Polygenic Risk Scores",
  "Adolescent Sexual & Reproductive Health",
  "Elder Mistreatment in Emergency Settings",
  "COVID-19 Informatics & Predictive Modeling",
  "Gut Microbiome, Diet & Host Metabolism",
  "Global Health Systems in Low-Income Countries",
  "Radiation Therapy Planning & Radiobiology",
  "Myeloproliferative Neoplasms & MDS",
  "Pediatric ED Acute Illness & Management",
  "Wearables & Remote Patient Monitoring",
  "Inflammatory Arthritis & Rheumatic Disease",
  "Protein Aggregation & Neurodegeneration",
  "Tumor Microenvironment & Cancer Immunity",
  "Systemic Therapy Resistance in Colorectal & Gastric Cancer",
  "Intraoperative Mapping & Awake Craniotomy",
  "IVF & Assisted Reproduction Outcomes",
  "Perinatal & Reproductive Mental Health",
  "Disorders of Consciousness & Clinical Ethics",
  "MS Disease-Modifying Therapy Outcomes",
  "Microbiome-Metabolite & Bile Acid Signaling",
  "Opioid Use & Drug Policy Research",
  "Proteomics & Cell Surface Characterization",
  "STI Epidemiology, Prevention & Vaccines",
  "Elder Abuse & Mistreatment Screening",
  "Fatty Liver Disease & Metabolic Steatohepatitis",
  "Lung Cancer Screening & Racial Disparities",
  "Spinal Trauma in Low-Resource Settings",
  "Generative AI in Clinical Applications",
  "Maternal Cytomegalovirus & Congenital Infection",
  "HIV & Infectious Disease Translational Research",
  "Movement Disorders & Neuromodulation",
  "Liver Transplantation Access & Outcomes",
  "Obesity & Metabolic Disease Pharmacotherapy",
  "Patient-Reported Outcomes & Quality of Life",
  "Peritoneal Dialysis Infection & Management",
  "Stroke & Cerebrovascular Disease Epidemiology",
  "Tuberculosis & Mycobacterial Infections",
  "Telehealth in Low- & Middle-Income Countries",
  "Infectious Complications in Transplant Recipients",
  "Cancer Molecular & Genomic Profiling",
  "Disability Rights & Crisis Resource Allocation",
  "Pain & Symptom Management in Serious Illness",
  "Lung Transplantation Perioperative Outcomes",
  "Obesity & Nutrition in Cancer Survivors",
  "Psychiatric Comorbidities in Serious Illness",
  "Thoracic Trauma & Perioperative Complications",
  "Medical Imaging Standards & Reproducibility",
  "Leadless Pacing & Cardiac Implant Devices",
  "Prostate Cancer Molecular Biology & Genomics",
  "Adipocyte Differentiation & Metabolic Regulation",
];

export const HERO_SEARCH_SUGGESTIONS: readonly string[] = [
  ...DEPARTMENTS,
  ...TOPICS,
  ...SUBTOPICS,
];

/**
 * Pick `n` distinct random entries from the suggestion pool. Server-renders
 * a fresh sample on every page load.
 */
export function sampleHeroSuggestions(n: number): string[] {
  const pool = [...HERO_SEARCH_SUGGESTIONS];
  for (let i = pool.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [pool[i], pool[j]] = [pool[j], pool[i]];
  }
  return pool.slice(0, Math.max(0, Math.min(n, pool.length)));
}
