/**
 * Seed parser + validator for the CTL available-technologies ETL.
 *
 * Split out of index.ts (mirroring `etl/mesh-aliases/csv.ts`) so the validation
 * can be unit-tested without running the importer's `main()`.
 *
 * The seed is machine-generated by `scripts/scrape-ctl-technologies.ts`, so it
 * is JSON, not CSV — `JSON.parse` replaces the hand-rolled RFC-4180 tokenizer
 * the hand-edited curated CSVs need.
 */

export type TechnologyRow = {
  cwid: string;
  reference: string | null;
  title: string;
  url: string;
  /** CTL patent status, e.g. "US Application Filed", "PCT Application Filed". */
  patentStatus: string | null;
  /** PMIDs of the papers CTL lists for this invention. Empty when none. */
  pmids: string[];
  /** CTL's "Technology Overview" as plain text; bullets joined one per line.
   *  Null when the page carries no overview section. */
  overview: string | null;
  /** True when the overview lists a "PoC Data" bullet. */
  hasPocData: boolean;
};

/** CTL's portfolio origin. Pinned — see `parseSeed`. */
export const CTL_ORIGIN = "https://innovation.weill.cornell.edu/";

const CWID_RE = /^[a-z0-9]{2,32}$/;
const PMID_RE = /^\d{6,9}$/;
/** Docket numbers are short plain text once tags are stripped. */
const PLAIN_TEXT_RE = /^[^<>]{1,64}$/;

/**
 * The closed vocabulary `normalizePatentStatus` may produce. Pinned here so a
 * regression in the normalizer surfaces as a failed run rather than raw CTL
 * prose ("US Patent 9,943,506 . \"BCL6 inhibitors...\"") on a public profile.
 */
export const PATENT_STATUSES: ReadonlySet<string> = new Set([
  "Provisional filed",
  "PCT filed",
  "Application filed",
  "Issued",
]);

/**
 * Parse + validate the seed. Throws on anything malformed rather than skipping
 * the row: a truncated or corrupt seed must fail the run, not quietly shrink
 * the table (the importer full-replaces).
 */
export function parseSeed(text: string): TechnologyRow[] {
  const raw: unknown = JSON.parse(text);
  if (!Array.isArray(raw)) throw new Error("[Technology] seed must be a JSON array");
  return validateRows(raw);
}

/**
 * Validate already-parsed rows. Applied to BOTH the checked-in seed and the
 * live scrape, so the guards below cover every path that can put text or an
 * href onto a public profile.
 */
export function validateRows(raw: unknown[]): TechnologyRow[] {
  const seen = new Set<string>();
  return raw.map((r, i) => {
    if (typeof r !== "object" || r === null)
      throw new Error(`[Technology] row ${i}: not an object`);
    const { cwid, reference, title, url, patentStatus, pmids, overview, hasPocData } =
      r as Record<string, unknown>;

    // CWIDs are lowercased directory usernames; legacy portfolio entries use
    // pre-2010 letter-only ids ("fisch", "cnathan"), so no digit is required.
    if (typeof cwid !== "string" || !CWID_RE.test(cwid)) {
      throw new Error(`[Technology] row ${i}: invalid cwid ${JSON.stringify(cwid)}`);
    }
    if (typeof title !== "string" || title.trim() === "") {
      throw new Error(`[Technology] row ${i} (${cwid}): title is required`);
    }
    // The url becomes an href on a public profile. Pin it to CTL's origin so a
    // corrupted or tampered seed cannot inject an off-site or `javascript:`
    // link. Prefix-matching a full origin (with trailing slash) is enough:
    // "https://innovation.weill.cornell.edu.evil.com/" fails the check.
    if (typeof url !== "string" || !url.startsWith(CTL_ORIGIN)) {
      throw new Error(`[Technology] row ${i} (${cwid}): url must start with ${CTL_ORIGIN}`);
    }

    // `reference` renders as text on a public profile. CTL's editors wrap the
    // docket in stray inline markup on some pages and the scraper strips it — a
    // surviving angle bracket means the strip failed, and React would render
    // escaped tags at the reader (`&lt;span&gt;9220&lt;/span&gt;`, which shipped
    // to staging once). Fail the run rather than ship that again.
    if (reference !== null && reference !== undefined) {
      if (typeof reference !== "string" || !PLAIN_TEXT_RE.test(reference)) {
        throw new Error(
          `[Technology] row ${i} (${cwid}): reference must be plain text of 1-64 chars with no angle brackets, got ${JSON.stringify(reference)}`,
        );
      }
    }

    // patentStatus is a chip label, drawn from a closed vocabulary.
    if (patentStatus !== null && patentStatus !== undefined) {
      if (typeof patentStatus !== "string" || !PATENT_STATUSES.has(patentStatus)) {
        throw new Error(
          `[Technology] row ${i} (${cwid}): patentStatus must be one of ${[...PATENT_STATUSES].join(" | ")} or null, got ${JSON.stringify(patentStatus)}`,
        );
      }
    }

    if (pmids !== undefined && !Array.isArray(pmids)) {
      throw new Error(`[Technology] row ${i} (${cwid}): pmids must be an array`);
    }
    const pmidList = (pmids ?? []) as unknown[];
    for (const p of pmidList) {
      // A pmid becomes a pubmed.ncbi.nlm.nih.gov href — digits only, no path escape.
      if (typeof p !== "string" || !PMID_RE.test(p)) {
        throw new Error(`[Technology] row ${i} (${cwid}): invalid pmid ${JSON.stringify(p)}`);
      }
    }

    // `overview` renders as TEXT (React escapes it), so angle brackets are fine —
    // they come from `&lt;`/`&gt;` in CTL's prose (e.g. "LC50 < 50nM"). Guard only
    // type, control bytes (the newlines that join bullets are exempt), and a
    // length ceiling matching the scraper's slice, so a tampered seed can't smuggle
    // a NUL onto a profile or blow the TEXT column.
    if (overview !== null && overview !== undefined) {
      if (typeof overview !== "string") {
        throw new Error(`[Technology] row ${i} (${cwid}): overview must be a string or null`);
      }
      if (/[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]/.test(overview)) {
        throw new Error(`[Technology] row ${i} (${cwid}): overview carries control characters`);
      }
      if (overview.length > 8000) {
        throw new Error(`[Technology] row ${i} (${cwid}): overview exceeds 8000 chars`);
      }
    }
    if (hasPocData !== undefined && typeof hasPocData !== "boolean") {
      throw new Error(`[Technology] row ${i} (${cwid}): hasPocData must be a boolean`);
    }

    // (cwid, url) is the table's unique key — a dupe would fail mid-transaction.
    const key = `${cwid} ${url}`;
    if (seen.has(key)) throw new Error(`[Technology] row ${i}: duplicate (cwid, url) for ${cwid}`);
    seen.add(key);

    return {
      cwid,
      reference: (reference as string | null | undefined) ?? null,
      title: title.trim(),
      url,
      patentStatus: (patentStatus as string | null | undefined) ?? null,
      pmids: pmidList as string[],
      overview: (overview as string | null | undefined) ?? null,
      hasPocData: hasPocData === true,
    };
  });
}
