/**
 * VIVO → Scholars URL redirect map generator (Phase 5 / SEO-04).
 *
 * Generates an nginx RewriteMap file that the VIVO nginx server consumes
 * to issue 301 redirects from `/display/cwid-{cwid}` → the current
 * Scholars canonical URL `/scholars/{slug}`.
 *
 * Output file format (one entry per line):
 *   # comment lines start with #
 *   {raw-cwid} {full-https-url};
 *
 * The nginx server config consuming this file MUST set:
 *   map_hash_max_size 16384;
 *   map_hash_bucket_size 128;
 * in the http {} block before `include`-ing this file inside a
 * `map $cwid_extracted $scholars_redirect { ... }` block. Default
 * `map_hash_max_size` (2048) is too small for ~9,000 entries.
 *
 * Run on demand at cutover prep time (NOT integrated into daily ETL):
 *   npm run etl:vivo-redirect
 *   # outputs to: etl/vivo-redirect/output/vivo-redirect.map
 *
 * Decisions:
 * - D-01: redirect scope is /display/cwid-{cwid} only (people profiles)
 * - D-02: active scholars 301 → /scholars/{slug}
 * - D-03: deleted/unknown CWIDs fall through to nginx 404 (no entry in map)
 * - D-05: cwid_aliases included so old CWIDs that map to a new live
 *         CWID also redirect to the live scholar's current slug
 */

import { writeFile, mkdir } from "node:fs/promises";
import path from "node:path";
import { prisma } from "../../lib/db";

const DEFAULT_BASE_URL = "https://scholars.weill.cornell.edu";
const DEFAULT_OUTPUT_PATH = path.join(
  __dirname,
  "output",
  "vivo-redirect.map",
);

export type MapScholar = { cwid: string; slug: string };
export type MapAlias = { oldCwid: string; currentCwid: string };

/**
 * Pure builder used by the unit test. Given the projected scholar list
 * (already filtered to active + non-deleted upstream) and the alias
 * list (already filtered to aliases pointing at active scholars), emit
 * the map file content as an array of strings (one element per line).
 *
 * The caller can join with '\n' to produce the final file text.
 */
export function buildVivoMapLines(
  scholars: MapScholar[],
  aliases: MapAlias[],
  baseUrl: string = DEFAULT_BASE_URL,
): string[] {
  const lines: string[] = [];
  lines.push(
    "# VIVO → Scholars redirect map — generated by etl/vivo-redirect/generate-map.ts",
  );
  lines.push(
    "# Format: <raw-cwid> <target-url>;  (one entry per line, semicolon-terminated)",
  );
  lines.push(
    "# nginx config requires: map_hash_max_size 16384; map_hash_bucket_size 128;",
  );
  lines.push(
    "# Consumed by VIVO nginx /display/cwid-(.+) location; deleted/unknown CWIDs fall through to 404 (D-03).",
  );
  lines.push("");

  // Index live scholars by cwid for alias resolution
  const liveByCwid = new Map<string, MapScholar>();
  for (const s of scholars) liveByCwid.set(s.cwid, s);

  for (const s of scholars) {
    lines.push(`${s.cwid}\t${baseUrl}/scholars/${s.slug};`);
  }

  for (const a of aliases) {
    const live = liveByCwid.get(a.currentCwid);
    if (!live) continue; // alias points at a non-live scholar — drop
    // Alias key (oldCwid) resolves to the LIVE scholar's current slug (D-05)
    lines.push(`${a.oldCwid}\t${baseUrl}/scholars/${live.slug};`);
  }

  return lines;
}

export async function main(): Promise<void> {
  const baseUrl = process.env.NEXT_PUBLIC_SITE_URL ?? DEFAULT_BASE_URL;

  // D-05 query: only active scholars, only aliases pointing at active scholars
  const [scholars, aliases] = await Promise.all([
    prisma.scholar.findMany({
      where: { deletedAt: null, status: "active" },
      select: { cwid: true, slug: true },
    }),
    prisma.cwidAlias.findMany({
      where: { current: { deletedAt: null, status: "active" } },
      select: { oldCwid: true, currentCwid: true },
    }),
  ]);

  const lines = buildVivoMapLines(scholars, aliases, baseUrl);
  const text = lines.join("\n") + "\n";

  const outputPath =
    process.env.SCHOLARS_VIVO_REDIRECT_OUTPUT ?? DEFAULT_OUTPUT_PATH;
  await mkdir(path.dirname(outputPath), { recursive: true });
  await writeFile(outputPath, text, "utf8");

  const total = scholars.length + aliases.length;
  console.log(
    `[vivo-redirect] wrote ${total} entries (${scholars.length} active scholars + ${aliases.length} aliases) to ${outputPath}`,
  );

  await prisma.$disconnect();
}

// Allow `tsx etl/vivo-redirect/generate-map.ts` to run main();
// skip auto-execution when imported as a module (e.g., from unit tests).
if (
  process.argv[1] &&
  (process.argv[1].endsWith("generate-map.ts") ||
    process.argv[1].endsWith("generate-map.js"))
) {
  main().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}
